### ISSUE TITLE
Favicons question

### ISSUE THREAD

**Issue by kalinchernev** [greglobinski/gatsby-starter-personal-blog#14]
In `package.json` there is a dependency to `gatsby-plugin-favicon` however there's no use of it in the `gatsby-config.js`. Trying to make use of the plugin and going through its issue queue, it seems to me that there is a problem with the `gatsby-plugin-favicon` working well with `gatsby-plugin-manifest`.

With relation to this, I was wondering:
- it seems it's the `gatsby-plugin-manifest` plugin doing the job and not the `gatsby-plugin-favicon`, so it could be removed?
- are you open for pull requests taking the favicons generation logic out of the `package.json`'s scripts and making a more readable/maintainable script file?

If this is not the case and the plugin is used, please ignore the self-reflection :P

**Comment by greglobinski** [comment]
@kalinchernev 

First, you are right, the starter does not use `gatsby-plugin-favicon`. I tried it but eventually I backed out. It should be removed from `package.json`. 

Second, when I added the `gatsby-plugin-manifest` to the starter it had not an icon generation functionality. There was only one mode 'manual', although it was not called this way :). Of course, now we can use the `automatic` mode of the plugin! I'm open for PR. Thank you for pointing this out. 

Third. because of apple, we still have additional job to do. Apple does not support transparent background in icons and does not get icons from `manifest.json` (https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7), so we still have to generate a separate icon set for apple (by mdn scripts)  and add them directly to the `<head>` in `html.js`. Of course in the case, when we do not want to use background transparent icons for android we do not have to generate another one set of icons, but I think that the starter should have this option.

Summarizing, If you are ready to clean this mess your PR will be welcome :)

**Comment by kalinchernev** [comment]
Hi @greglobinski and thanks for your reply on Sunday :)

I opened a small PR to remove the dependency to unused `gatsby-plugin-favicon`, the rest is simply moved to a file that makes it a bit easier to maintain the separate image generation tasks. So, existing assets and functionalities should be intact.

I'll read a bit more about the edge cases and the new option in the `gatsby-plugin-manifest`, some new info to take in :)

Closing this one, as it was a question with a doable step to solve the unneeded dep :)

Thanks!
