### ISSUE TITLE
APNG issue

### ISSUE THREAD

**Issue by jampy** [greglobinski/gatsby-starter-personal-blog#16]
Great starter, congratulations!

I'd like to use it for a site that is currently based on `gatsby-styled-blog-starter` and moved the posts from there.

It seems to work very well, but for some strange reason transparency in PNG files is transformed some how.

![image](https://user-images.githubusercontent.com/820758/38581621-ad9dc876-3d0d-11e8-8731-47490f48d060.png)

It should be displayed like so:

![image](https://user-images.githubusercontent.com/820758/38581640-ba861cb4-3d0d-11e8-9b52-0d55371dfa13.png)

Currently I'm using exactly the `gatsby-starter-personal-blog` source with just the `content/posts` directory replaced.

**Comment by greglobinski** [comment]
@jampy 
If you want the same behavior as it is in `gatsby-styled-blog-starter` remove ` backgroundColor: "transparent"` from the `gatsby-remark-images` setup in `gatsby-config.js`
```
{
    resolve: `gatsby-remark-images`,
    options: {
        maxWidth: 800,
        backgroundColor: "transparent"
    }
}
``` 
but then you will turn off 'blur up' effect which is not what we usually want. I opened an issue about this https://github.com/gatsbyjs/gatsby/issues/4510

In your case however, there is no other option because the 'blur up' effect will not work correctly with transparent background images. If you want see the 'blur up' effect you have to give up on using transparent background images.

**Comment by jampy** [comment]
Thanks, that helps.

BTW, I wouldn't say that the "blur up" effect with such graphics is bad. It would work fine if the the blurred data-URI `background-image` would be removed after the "blur up". Alternatively, the blurred image could fade-out for a more smooth transition.

Anyway, I can live without the blur-up. Thanks again.

**Comment by greglobinski** [comment]
@jampy ,
yup,  that's a personal aesthetic preference. I feel that a blurred placeholder bigger and different in shape  than a target graphic will look weird. Yes fading out the blurred placeholder after the target image load would help. But still the blurred placeholder with different shape could look unconnected.. But that's only my hunch.
