### ISSUE TITLE
Why each page has a number "3" behind the URL

### ISSUE THREAD

**Issue by izuolan** [greglobinski/gatsby-starter-personal-blog#4]
In addition, when I click the avatar picture to return homepage(or category filter), the URL does not change.

**Comment by greglobinski** [comment]
@izuolan Are you talking about this "3" at the end of, for example, the url `https://gatsby-starter-personal-blog.greglobinski.com/like-nonsense-3/`? It's just a part of url, nothing special with it. And it's not true that every page has the "3" in its url, only one-third of them has it.

Yep, it's intentional behavior. There is a commented code in `src/utils/shared.js` 

```

**Comment by greglobinski** [comment]
```
