### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by funkymonkeymonk** [greglobinski/gatsby-starter-personal-blog#48]
Hello glorious maintainer =-)

Do you have any suggestions or recommendations for how to upgrade to the latest version of your template from a previous version? I'm about to start diff'g but I wanted to make sure I wasn't doing something stupid and missing the obvious.

**Comment by greglobinski** [comment]
@funkymonkeymonk 
Interesting question, I did not think about that. It's a 'theme like' but it's still a starter, so there is no troublefree way to 'upgrade', I think.

If someone is planing to use the starter as it is, of course with changes in the content, I would use `git clone ...` instead of `gatsby new ...` at the beginning and later try to `git rebase` incoming upgrades of the starter. But I have not tried and I am not sure if that would work but seams that it should.
