### ISSUE TITLE
Getting BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by siwalikm** [greglobinski/gatsby-starter-personal-blog#66]
Just forked the project and trying to run `gatsby develop` which is giving me BrowserslistError: Unknown browser query `dead`.
![image](https://user-images.githubusercontent.com/20061595/46016695-12374c80-c0f3-11e8-9e5f-3b5fb5517984.png)

**Comment by greglobinski** [comment]
@siwalikm you probably has  `gatsby-cli` v 2.4.1 installed globally.

This is a starter for Gatsby v1, it seems that it has problem with `gatsby-cli` v2. The workaround the issue is to use local `gatsby-cli`

The convenient way is to update `package.json`

```
  "scripts": {
    "build": "./node_modules/.bin/gatsby build",
    "develop": "./node_modules/.bin/gatsby develop",
   ...
```

and instead `gatsby develop` and `gatsby build` use `yarn develop` and `yarn build`

**Comment by siwalikm** [comment]
Hi Greg, Thanks a lot, this solved the issue for me. Shall I add a note to the `readme.md` ?

**Comment by greglobinski** [comment]
@siwalikm 
Sure. Thank you

**Comment by suhaschitade** [comment]
Hi Greg, 
Tried above. when I excuted command gatsby build it results in same error

success delete html and css files from previous builds — 0.043 s
success open and validate gatsby-config — 0.025 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.056 s
success onPreBootstrap — 8.508 s
success source and transform nodes — 1.717 s
success building schema — 0.899 s
success createLayouts — 0.010 s
success createPages — 0.121 s
success createPagesStatefully — 0.023 s
success onPreExtractQueries — 0.009 s
success update schema — 0.142 s
success extract queries from components — 0.205 s
success run graphql queries — 3.630 s
success write out page data — 0.008 s
success write out redirect data — 0.006 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 29.591 s


error Generating CSS failed
  BrowserslistError: Unknown browser query `dead`
  
  - index.js:37 error
    [blog]/[browserslist]/index.js:37:11

thanks,
Suhas

**Comment by greglobinski** [comment]
@suhaschitade https://github.com/gatsbyjs/gatsby/issues/8575#issuecomment-425018353
