### ISSUE TITLE
Code highlighting does not work using prismjs

### ISSUE THREAD

**Issue by RanjeetAulakh** [greglobinski/gatsby-starter-personal-blog#8]
Go to link 
https://gatsby-starter-personal-blog.greglobinski.com/like-nonsense-3/
on the demo website code highlighting does not work.
I have similar setup and can not make the code highlighting work.
on using `gatsby develop` highlighting works as intended but not when use `gatsby build`

**Comment by greglobinski** [comment]
@RanjeetAulakh  thanks for feedback.
The issue is fixed. After choosing `react-jss` as a CSS manager I removed the code responsible for CSS SSR. But `prismjs` needs it so put it back to `html.js`.

Details are here [Add CSS rendering to html.js](https://github.com/greglobinski/gatsby-starter-personal-blog/commit/5f4e84474593f5fe6f90687aa4807b09670af4c4)

Thanks

**Comment by RanjeetAulakh** [comment]
Yes i can confirm the issue is fixed now, Thanks for the prompt response and contribution to open source community.
